### ISSUE TITLE
Not able to livestyle after multiple tries

### ISSUE THREAD

**Issue by derekhargest** [emmetio/livestyle-sublime-old#116]
Ive been trying to work with this in a couple places and follow the instructions to the T and it never works properly. Here is my log file.

startup, version: 2221 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/derek/Library/Application Support/Sublime Text 2/Packages
settings path: /Users/derek/Library/Application Support/Sublime Text 2/Settings
PackageSetup not required
catalogue loaded
found 5 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 4 files for base name Main.sublime-menu
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/CSS/css_completions.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/comment.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/copy_path.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/delete_word.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/detect_indentation.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/duplicate_line.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/echo.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/exec.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/fold.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/font.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/goto_line.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/indentation.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/kill_ring.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/mark.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/new_templates.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/open_file_settings.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/open_in_browser.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/paragraph.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/scroll.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/side_bar.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/sort.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/swap_line.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/switch_file.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/transform.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/transpose.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Diff/diff.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/HTML/html_completions.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/LiveStyle/livestyle.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Package Control/Package Control.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/SFTP/SFTP.py
plugin init time: 1.51357
loading pointer bindings
loading bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 1.97088
using gamma: 2 (err: 6.9282)
wrote startup cache, added files: 9 orphaned files: 0 total files: 102 cache hits: 93
startup time: 2.41881 (package setup was not run)
loaded 837 snippets
Package Control: Skipping automatic upgrade, last run at 2014-05-26 15:04:14, next run at 2014-05-26 16:04:14 or after
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/logging/**init**.py", line 800, in emit
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/logging/**init**.py", line 761, in flush
    if self.stream and hasattr(self.stream, "flush"):
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0131' in position 91: ordinal not in range(128)
Writing file /Users/derek/Library/Application Support/Sublime Text 2/Packages/LiveStyle/LiveStyle.sublime-settings with encoding UTF-8
reloading /Users/derek/Library/Application Support/Sublime Text 2/Packages/LiveStyle/LiveStyle.sublime-settings
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Writing file /var/folders/7m/m6yjh8xx1dl2mcln0wq6hbtc0000gn/T/sublime-sftp-browse-1401131285/intervention/home/cemarket/www/demo/intervention/_css/styles.css with encoding UTF-8
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Writing file /var/folders/7m/m6yjh8xx1dl2mcln0wq6hbtc0000gn/T/sublime-sftp-browse-1401131285/intervention/home/cemarket/www/demo/intervention/_css/styles.css with encoding UTF-8
Emmet LiveStyle: No suitable client for diff
Writing file /var/folders/7m/m6yjh8xx1dl2mcln0wq6hbtc0000gn/T/sublime-sftp-browse-1401131285/intervention/home/cemarket/www/demo/intervention/_css/styles.css with encoding UTF-8
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: No suitable client for diff
Writing file /var/folders/7m/m6yjh8xx1dl2mcln0wq6hbtc0000gn/T/sublime-sftp-browse-1401131285/intervention/home/cemarket/www/demo/intervention/_css/styles.css with encoding UTF-8

Any help?
##

**Comment by sergeche** [comment]
`Emmet LiveStyle: No suitable client for diff` means there’s no running client (e.g. opened DevTools panel)

**Comment by derekhargest** [comment]
Always have the Dev Tools open tried in both Chrome with tools in its own window and connected to the browser: Here's another try's log.

startup, version: 2221 osx x64 channel: stable
executable: /Applications/Sublime Text 2.app/Contents/MacOS/Sublime Text 2
working dir: /
packages path: /Users/derek/Library/Application Support/Sublime Text 2/Packages
settings path: /Users/derek/Library/Application Support/Sublime Text 2/Settings
PackageSetup not required
catalogue loaded
found 5 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 4 files for base name Main.sublime-menu
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/CSS/css_completions.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/comment.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/copy_path.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/delete_word.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/detect_indentation.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/duplicate_line.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/echo.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/exec.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/fold.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/font.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/goto_line.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/indentation.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/kill_ring.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/mark.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/new_templates.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/open_file_settings.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/open_in_browser.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/paragraph.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/save_on_focus_lost.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/scroll.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/side_bar.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/sort.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/swap_line.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/switch_file.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/transform.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/transpose.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Diff/diff.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/HTML/encode_html_entities.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/HTML/html_completions.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/LiveStyle/livestyle.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/Package Control/Package Control.py
Reloading plugin /Users/derek/Library/Application Support/Sublime Text 2/Packages/SFTP/SFTP.py
plugin init time: 1.85841
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 2.92464
using gamma: 2 (err: 6.9282)
Emmet LiveStyle: client connected
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Prepare diff
startup cache, total files: 102 cache hits: 102
startup time: 3.52707 (package setup was not run)
Emmet LiveStyle: Sending ws message '{"action": "id", "data": {"files": ["/var/folders/7m/m6yjh8xx1dl2mcln0wq6hbtc0000gn/T/sublime-sftp-browse-1401131285/intervention/home/cemarket/www/demo/intervention/_css/styles.css"], "icon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABu0lEQVR42q2STWsTURhG3WvdCyq4CEVBAgY
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/var/folders/7m/m6yjh8xx1dl2mcln0wq6hbtc0000gn/T/sublime-sftp-browse-1401131285/intervention/home/cemarket/www/demo/intervention/_css/styles.css"]}'
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/var/folders/7m/m6yjh8xx1dl2mcln0wq6hbtc0000gn/T/sublime-sftp-browse-1401131285/intervention/home/cemarket/www/demo/intervention/_css/styles.css"]}'
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/var/folders/7m/m6yjh8xx1dl2mcln0wq6hbtc0000gn/T/sublime-sftp-browse-1401131285/intervention/home/cemarket/www/demo/intervention/_css/styles.css"]}'
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/var/folders/7m/m6yjh8xx1dl2mcln0wq6hbtc0000gn/T/sublime-sftp-browse-1401131285/intervention/home/cemarket/www/demo/intervention/_css/styles.css"]}'
loaded 837 snippets
Package Control: Skipping automatic upgrade, last run at 2014-05-26 15:04:14, next run at 2014-05-26 16:04:14 or after
Reloading /var/folders/7m/m6yjh8xx1dl2mcln0wq6hbtc0000gn/T/sublime-sftp-browse-1401131285/intervention/home/cemarket/www/demo/intervention/_css/styles.css
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: Prepare diff
Emmet LiveStyle: Sending ws message '{"action": "updateFiles", "data": ["/var/folders/7m/m6yjh8xx1dl2mcln0wq6hbtc0000gn/T/sublime-sftp-browse-1401131285/intervention/home/cemarket/www/demo/intervention/_css/styles.css"]}'
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Emmet LiveStyle: Run diff
Emmet LiveStyle: No suitable client for diff
Writing file /var/folders/7m/m6yjh8xx1dl2mcln0wq6hbtc0000gn/T/sublime-sftp-browse-1401131285/intervention/home/cemarket/www/demo/intervention/_css/styles.css with encoding UTF-8

Thanks for the help!

**Comment by derekhargest** [comment]
I have also reinstalled Chrome, Sublime text and the respective extensions.

**Comment by sergeche** [comment]
What’s your LiveStyle for Chrome extension version?

**Comment by derekhargest** [comment]
0.8.2.1230 - recently reinstalled

**Comment by sergeche** [comment]
From your log I can see that there was no `handshake` message from client (Chrome): either it’s outdated or you have proxy or something. Can you show me a screenshot of your Chrome Extensions page?
