### ISSUE TITLE
Deesn't work after recent update

### ISSUE THREAD

**Issue by Kotpes** [emmetio/livestyle-sublime-old#128]
Stopped working after recent release. Mac OS X 10.10 beta 6, Sublime Text 3 (latest).
Sublime sees the plugin but changes done in Dev tools never appear in css
Console:
startup, version: 3065 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/kotpes/Library/Application Support/Sublime Text 3/Packages
state path: /Users/kotpes/Library/Application Support/Sublime Text 3/Local
hardware concurrency: 4
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/kotpes/Library/Application Support/Sublime Text 3/Installed Packages
found 8 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 10 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 1 orphaned files: 1 total files: 235 cache hits: 234
pre session restore time: 0.989225
using gamma: 2 (err: 6.9282)
first paint time: 1.08336
startup time: 1.09754
launching: /Applications/Sublime Text.app/Contents/MacOS/plugin_host
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Emmet.emmet-plugin
reloading plugin HTMLBeautify.HTMLBeautify
reloading plugin LESS.less_completions
reloading plugin LiveReload.livereload_st2
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "livereload_st2 in /Users/kotpes/Library/Application Support/Sublime Text 3/Installed Packages/LiveReload.sublime-package", line 21
    except Exception, u:
                    ^
SyntaxError: invalid syntax
reloading plugin LiveStyle.livestyle
loaded 3476 snippets
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.Edit
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarEnhancements.StatusBarFileSize
reloading plugin SideBarEnhancements.StatusBarModifiedTime
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Autoprefixer.node_bridge
reloading plugin SFTP.SFTP
plugins loaded
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2014-09-04 15:22:19, next run at 2014-09-04 16:22:19 or after
Emmet LiveStyle: No unsaved changes
Emmet LiveStyle: No unsaved changes
##

**Comment by devonmather** [comment]
Same issue on mavericks, 'editor is undefined' or 'no active editor' despite sublime being open.

**Comment by sergeche** [comment]
I’m working on a new Chrome extension, please wait :)

**Comment by devonmather** [comment]
Thank you :)

**Comment by Justforfei** [comment]
same problem
