### ISSUE TITLE
LiveStyle "stopped working" + not showing CSS styles in DevTools > Elements > Styles

### ISSUE THREAD

**Issue by Goodnewstown** [emmetio/livestyle-sublime-old#129]
Hello, it is the 2nd day I am having hard times with Google Chrome and LiveStyle. 
Seems my LiveStyle doesn't want to work anymore. Cant make css changes on the fly, simply there is no style name for site elements anymore but the proper css styles chosen in LiveStyle menu in DevTools. 

![livestyleproblem](https://cloud.githubusercontent.com/assets/6180178/4693059/561099ee-5788-11e4-92bf-6bfc774dce47.jpg)

here is the log, please advise, thank you.

DPI scale: 1
startup, version: 3065 windows x32 channel: stable
executable: /C/Program Files (x86)/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files (x86)/Sublime Text 3
packages path: /C/Users/computer/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/computer/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 4
zip path: /C/Program Files (x86)/Sublime Text 3/Packages
zip path: /C/Users/computer/AppData/Roaming/Sublime Text 3/Installed Packages
found 9 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 6 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
startup cache, total files: 195 cache hits: 195
pre session restore time: 0.091384
startup time: 0.129384
first paint time: 0.134384
launching: /C/Program Files (x86)/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Compare Side-By-Side.sbs_compare
reloading plugin LiveStyle.livestyle
loaded 1005 snippets
reloading plugin Package Control.Package Control
reloading plugin Require Node.js Modules Helper.Edit
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1512, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1512, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in _find_and_load_unlocked
ImportError: No module named 'Require Node'
reloading plugin Require Node.js Modules Helper.require_node
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1512, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1512, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in _find_and_load_unlocked
ImportError: No module named 'Require Node'
reloading plugin Tag.Edit
reloading plugin Tag.Tag
reloading plugin Tag.tag_close_tag
reloading plugin Tag.tag_close_tag_on_slash
reloading plugin Tag.tag_indent
reloading plugin Tag.tag_insert_as_tag
reloading plugin Tag.tag_lint
reloading plugin Tag.tag_remove
reloading plugin Tag.tag_remove_attributes
reloading plugin PyV8
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\computer\AppData\Roaming\Sublime Text 3\Packages\PyV8.py", line 32, in <module>
    import _PyV8
ImportError: DLL load failed: %1 не является приложением Win32.
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin PyV8.PyV8
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1512, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\computer\AppData\Roaming\Sublime Text 3\Packages\PyV8.py", line 32, in <module>
    import _PyV8
ImportError: DLL load failed: %1 не является приложением Win32.
reloading plugin User.PyV8
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sublime Text 3\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\computer\AppData\Roaming\Sublime Text 3\Packages\User\PyV8.py", line 32, in <module>
    import _PyV8
ImportError: DLL load failed: %1 не является приложением Win32.
plugins loaded
Package Control: No updated packages
##

**Comment by sergeche** [comment]
LiveStyle can’t break DevTools CSS pane, it simply has no access to it. Make you’re using most recent stable Chrome version

**Comment by Goodnewstown** [comment]
I am using the latest version - 38.0.2125.104 m (well, as far as Chrome tells me).
I'll try to describe my problem in other words.
Everything worked fine till recent days. I've been using ST3 with LiveStyle Chrome extenstion fine for months.
But lately DevTools > Elements > Styles column does not show the specific CSS this or that HTML element uses. So when I make changes to the css rules in Chrome they don't appear in Sublime opened CSS file though the css styles assigned in LiveStyle panel in DevTool window. 
My thoughts were, that my settings are messed up, but I can't find where exactly. 
Every piece of the puzzle seems to be installed, but there is something wrong. Maybe some plugin or so.
![livestyleproblem2](https://cloud.githubusercontent.com/assets/6180178/4721680/296ce1be-593a-11e4-81e3-7b65bb3923fa.jpg)

Apart from Chrome version is where any other solution/way to figure the problem out?

**Comment by vandroids** [comment]
Exactly the same issue after my Win7 Chrome has been updated to 38.0.2125.104 m

**Comment by Goodnewstown** [comment]
Got it fixed! My solution:
- back up all chrome settings into the cloud (preferences > google account > sign in);
- uninstall after closing chrome;
- downloaded a previous stable version (37.0.2062.102), used some torrent for that;
- restarted the PC;
- turned the internet off;
- disabled "automatic update" in chrome (chrome://plugins/);
- switched back online and got all my chrome settings back and a working ST3 + LiveStyle! ;]
  ![screenshot_1](https://cloud.githubusercontent.com/assets/6180178/4759452/634cdcc8-5ae7-11e4-98a9-ce56eaf894a0.jpg)
  till the next version of chrome proves its stability with LiveStyle. Cheers!
  And thanks to Sergeche, the root was in Chrome.

**Comment by Goodnewstown** [comment]
Though the issue is still there. And I want to believe the cause will be found so we all would not wind up LiveStyleLess with newer Google Chrome versions.
