### ISSUE TITLE
Can't run LiveStyle in ST2

### ISSUE THREAD

**Issue by agusguerra10** [emmetio/livestyle-sublime-old#27]
Hi!

I'm getting a "No active editor" message in Chrome and it seems that the problem is related to ST2 package.

Here is what I'm getting in ST2 console:

Reloading plugin pathToSublimeText2/Packages/LiveStyle/livestyle.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./livestyle.py", line 56, in <module>
    import lsutils.diff
  File "./lsutils/diff.py", line 314, in <module>
    lsutils.pyv8loader.load(lsutils.pyv8delegate.PYV8_PATHS[1], delegate)
  File "./lsutils/pyv8loader.py", line 47, in load
    config = get_loader_config(dest_path)
  File "./lsutils/pyv8loader.py", line 120, in get_loader_config
    for k,v in json.load(fd).items():
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/**init**.py", line 267, in load
    parse_constant=parse_constant, **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/**init**.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Do you have any idea about what could be causing this error?

Thanks!

Agus.

**Comment by sergeche** [comment]
For some reason, a `Packages/PyV8/osx/config.json` is invalid or empty. I’ve just pushed update that should fix this error. If it doesn’t, simply remove `Packages/PyV8/osx/config.json` file

**Comment by agusguerra10** [comment]
Working!! Thank you so much!! This tool is AWESOME!!

**Comment by agusguerra10** [comment]
Well.. it seems like the error disappeared and now I'm being able to select the file in chrome's plugin and map css to a file in sublime text. However, any changes made in the file or in chrome inspector, are not being reflected.
I'm not getting any message in sublime text console.

Thanks for your help!

Agus.

**Comment by sergeche** [comment]
Make sure your changes are not overridden by other rules, inspect your elements to see if new changes are applied. Also, you can go to `chrome://extensions/`, open `background.hrml` of LiveStyle and check its console for errors

**Comment by franciscolourenco** [comment]
I'm also getting the "No active editor" message on the chrome extension..
It worked before but stopped working..

Deleting `Packages/PyV8/osx/config.json` didn't work

Sublime 2.0.2 (2221)
LiveStyle Chrome extension 0.8.0.729

**Comment by franciscolourenco** [comment]
When I load the sublime package I get this:

```
reloading /Users/user/Dropbox/Library/Application Support/Sublime Text 2/Packages/LiveStyle/LiveStyle.sublime-settings
theme loaded
found 28 files for base name Main.sublime-menu
Traceback (most recent call last):
  File "./livestyle.py", line 202, in handle_settings_change
    return
AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "./livestyle.py", line 202, in handle_settings_change
    return
AttributeError: 'NoneType' object has no attribute 'get'
Emmet LiveStyle: Starting LiveStyle server on port 54000
```

**Comment by franciscolourenco** [comment]
Never mind, it wasn't working because of proxy settings..
