### ISSUE TITLE
 free variable 'e' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by webuniverseio** [emmetio/livestyle-sublime-old#34]
I'm getting error when trying to modify newly opened file (syntax css):

```
Traceback (most recent call last):
  File "D:\Program Files\Sublime Text 3\Data\Packages\livestyle-sublime\lsutils\editor.py", line 22, in <lambda>
    return lambda *args, **kwargs: sublime.set_timeout(lambda: fn(*args, **kwargs), 0)
  File "D:\Program Files\Sublime Text 3\Data\Packages\livestyle-sublime\lsutils\diff.py", line 161, in _err
    logger.error('Error: %s' % e)
NameError: free variable 'e' referenced before assignment in enclosing scope
```

**Comment by webuniverseio** [comment]
Thank you, works well.
