### ISSUE TITLE
No active editor on linux

### ISSUE THREAD

**Issue by sethstha** [emmetio/livestyle-sublime-old#53]
hello everyone

i am having the issue with google chrome and sublime text 3 in linux based distro elemetary os 2. i checked the plugin is quite working on sublime but says no active editor on chrome. is linux is still not supported or something else

Need a help badly

**Comment by sergeche** [comment]
Post your ST console log

**Comment by sethstha** [comment]
Ok the console log is here

DPI scale: 1
startup, version: 3047 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /home/sanjeev
packages path: /home/sanjeev/.config/sublime-text-3/Packages
state path: /home/sanjeev/.config/sublime-text-3/Local
hardware concurrency: 2
zip path: /opt/sublime_text/Packages
zip path: /home/sanjeev/.config/sublime-text-3/Installed Packages
found 6 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 6 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Soda Light 3.sublime-theme
theme loaded
app ready
startup cache, total files: 283 cache hits: 283
pre session restore time: 0.928735
using gamma: 1 (err: 0)
startup time: 1.41599
first paint time: 1.49018
launching: /opt/sublime_text/plugin_host
loaded 837 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin Emmet.emmet-plugin
reloading plugin LiveStyle.livestyle
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/**init**.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "livestyle in /home/sanjeev/.config/sublime-text-3/Installed Packages/LiveStyle.sublime-package", line 56, in <module>
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/home/sanjeev/.config/sublime-text-3/Installed Packages/LiveStyle.sublime-package/lsutils/diff.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/home/sanjeev/.config/sublime-text-3/Installed Packages/LiveStyle.sublime-package/lsutils/pyv8delegate.py", line 24, in <module>
  File "/home/sanjeev/.config/sublime-text-3/Installed Packages/LiveStyle.sublime-package/lsutils/pyv8loader.py", line 150, in unpack_pyv8
  File "X/zipfile.py", line 910, in __init__
  File "X/zipfile.py", line 944, in _GetContents
  File "X/zipfile.py", line 959, in _RealGetContents
zipfile.BadZipFile: File is not a zip file
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.Edit
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarEnhancements.StatusBarFileSize
reloading plugin SideBarEnhancements.StatusBarModifiedTime
plugins loaded
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2013-08-14 11:20:13, next run at 2013-08-14 12:20:13 or after

**Comment by sergeche** [comment]
Looks like there was a problem installing PyV8. Try to install it manually: https://github.com/emmetio/pyv8-binaries#manual-installation

**Comment by sergeche** [comment]
Just pushed update, it might fix this issue.
PS: make sure your Chrome extension is updated too to at least 0.8.0.816 version. Otherwise package won’t work.
