### ISSUE TITLE
ST3 and Mavericks problem

### ISSUE THREAD

**Issue by el** [emmetio/livestyle-sublime-old#7]
Here is the logs

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 71, in reload_plugin
    m = imp.reload(m)
  File "X/imp.py", line 252, in reload
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.**dict**)
  File "livestyle in /Users/eliz/Library/Application Support/Sublime Text 3/Installed Packages/LiveStyle.sublime-package", line 56, in <module>
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Users/eliz/Library/Application Support/Sublime Text 3/Installed Packages/LiveStyle.sublime-package/lsutils/diff.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Users/eliz/Library/Application Support/Sublime Text 3/Installed Packages/LiveStyle.sublime-package/lsutils/pyv8delegate.py", line 18, in <module>
  File "/Users/eliz/Library/Application Support/Sublime Text 3/Installed Packages/LiveStyle.sublime-package/lsutils/pyv8loader.py", line 101, in get_arch
  File "/Users/eliz/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/semver.py", line 81, in match
  File "/Users/eliz/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/semver.py", line 55, in compare
  File "/Users/eliz/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/semver.py", line 20, in parse
ValueError: 10.9 is not valid SemVer string
found 6 files for base name Main.sublime-menu
##

**Comment by sergeche** [comment]
Oh, Maverics... :) I’ll check it out

**Comment by sergeche** [comment]
Just pushed update that should fix it. Make sure both Emmet and LiveStyle packages are updated

**Comment by patrikholcak** [comment]
Updated all packages, this is the error I get

File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
  m = importlib.import_module(modulename)
File "X/importlib/**init**.py", line 88, in import_module
File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 671, in load_module
  exec(compile(source, source_path, 'exec'), mod.__dict__)
File "livestyle in ~/Library/Application Support/Sublime Text 3/Installed Packages/LiveStyle.sublime-package", line 56,< in <module>
File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
File "~/Library/Application Support/Sublime Text 3/Installed Packages/LiveStyle.sublime-package/lsutils/diff.py", line 14, in <module>
File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
File "~/Library/Application Support/Sublime Text 3/Installed Packages/LiveStyle.sublime-package/lsutils/pyv8delegate.py", line 18, in <module>
File "~/Library/Application Support/Sublime Text 3/Installed Packages/LiveStyle.sublime-package/lsutils/pyv8loader.py", line 101, in get_arch
File "~/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/semver.py", line 81, in match
File "~/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/semver.py", line 55, in compare
File "~/Library/Application Support/Sublime Text 3/Installed Packages/Emmet.sublime-package/emmet/semver.py", line 20, in parse
ValueError: 10.9 is not valid SemVer string

**Comment by sergeche** [comment]
@patrikholcak it means Emmet package is still outdated. Try to remove it and install again

**Comment by patrikholcak** [comment]
Oh, foolish me thought that when I hit Upgrade All, it upgrades all packages. Works like magic now. :)

**Comment by el** [comment]
Hey, thanks for the update. Can we use Safari 7? Webkit nightly build doesn't work on Mavericks. Chrome Extension works though...

**Comment by sergeche** [comment]
I had no chance to try Mavericks, but I think it should look similar to WebKit Nightly. You can try to manually install extension for Safari as described here: http://livestyle.emmet.io/install/#manual-installation But replace `WebKit.app` with `Safari.app`

**Comment by el** [comment]
The path should be `/System/Library/PrivateFrameworks/WebInspector.framework/Versions/Current/Resources` on mavericks however it doesn't look like it is loaded.
