### ISSUE TITLE
Windows XP no changes in Chrome from save in Sublime Text 3

### ISSUE THREAD

**Issue by ghost** [emmetio/livestyle-sublime-old#72]
Recently installed Livestyle via package control and installed the chrome extension. I have connected a local css file that is open in SublimeText 3 with the file the browser is loading. When editing and saving from Sublime Text 3 there is no change in Chrome.

I am running the site on a local host initiated from Visual Studio 2010 in Windows XP. Not sure if that might be the issue.
##

**Comment by sergeche** [comment]
Post your ST console log, please.

**Comment by ghost** [comment]
DPI scale: 1
startup, version: 3047 windows x32 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Documents and Settings/FlastA/Application Data/Sublime Text 3/Packages
state path: /C/Documents and Settings/FlastA/Application Data/Sublime Text 3/Local
hardware concurrency: 2
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Documents and Settings/FlastA/Application Data/Sublime Text 3/Installed Packages
found 6 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 6 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 2 orphaned files: 0 total files: 166 cache hits: 164
pre session restore time: 0.202926
startup time: 0.373926
first paint time: 0.405926
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
loaded 623 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Alignment.Alignment
reloading plugin Emmet.emmet-plugin
reloading plugin LiveStyle.livestyle
reloading plugin Package Control.Package Control
reloading plugin Sublimerge Pro.Sublimerge2
plugins loaded
found 6 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
loading pointer bindings
PyV8: Creating new thread
Emmet: Creating thread
Emmet: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
emmet.pyv8loader: Unable to download packages list. URL error [WinError 10061] No connection could be made because the target machine actively refused it downloading https://api.github.com/repos/emmetio/pyv8-binaries/contents.
Exception in thread Thread-14:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "X/threading.py", line 825, in run
  File "C:\Documents and Settings\FlastA\Application Data\Sublime Text 3\Installed Packages\Emmet.sublime-package\emmet\pyv8loader.py", line 271, in run
    return self.trigger('error', exit_code=self.thread.exit_code, progress=self)
  File "C:\Documents and Settings\FlastA\Application Data\Sublime Text 3\Installed Packages\Emmet.sublime-package\emmet\pyv8loader.py", line 290, in trigger
    c(_args, *_kwargs)
TypeError: on_error() got an unexpected keyword argument 'progress'

Package Control: Skipping automatic upgrade, last run at 2013-08-28 15:00:47, next run at 2013-08-28 16:00:47 or after
Writing file /C/Projects/Darwin/Darwin-UI-LookFeel/Darwin-UI/Content/Default/Styles/GlobalOptions.css with encoding UTF-8 with BOM (atomic)

**Comment by sergeche** [comment]
Please enable debug mode as described [here](https://github.com/emmetio/livestyle-sublime/blob/master/messages/install.txt) and send me ST log again but only after you edit your CSS and don’t receive expected updates

**Comment by ghost** [comment]
I added the line to the debug line to the livestyle prefs. Below is the console log:
DPI scale: 1
startup, version: 3047 windows x32 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Documents and Settings/FlastA/Application Data/Sublime Text 3/Packages
state path: /C/Documents and Settings/FlastA/Application Data/Sublime Text 3/Local
hardware concurrency: 2
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Documents and Settings/FlastA/Application Data/Sublime Text 3/Installed Packages
found 6 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 6 files for base name Main.sublime-menu
loading bindings
found 1 files for base name Default.sublime-theme
loading pointer bindings
theme loaded
app ready
wrote startup cache, added files: 2 orphaned files: 0 total files: 166 cache hits: 164
pre session restore time: 0.702462
startup time: 0.999462
first paint time: 1.03046
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
loaded 623 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Alignment.Alignment
reloading plugin Emmet.emmet-plugin
reloading plugin LiveStyle.livestyle
reloading plugin Package Control.Package Control
reloading plugin Sublimerge Pro.Sublimerge2
plugins loaded
found 6 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
PyV8: Creating new thread
Emmet: Creating thread
Emmet: Loading https://api.github.com/repos/emmetio/pyv8-binaries/contents
loading pointer bindings
emmet.pyv8loader: Unable to download packages list. URL error [WinError 10061] No connection could be made because the target machine actively refused it downloading https://api.github.com/repos/emmetio/pyv8-binaries/contents.
Exception in thread Thread-15:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "X/threading.py", line 825, in run
  File "C:\Documents and Settings\FlastA\Application Data\Sublime Text 3\Installed Packages\Emmet.sublime-package\emmet\pyv8loader.py", line 271, in run
    return self.trigger('error', exit_code=self.thread.exit_code, progress=self)
  File "C:\Documents and Settings\FlastA\Application Data\Sublime Text 3\Installed Packages\Emmet.sublime-package\emmet\pyv8loader.py", line 290, in trigger
    c(_args, *_kwargs)
TypeError: on_error() got an unexpected keyword argument 'progress'

Package Control: Installing 3 upgrades
ignored packages updated to: [SideBarEnhancements, SideBarGit, Rails, keeganstreet-sublime-elfinder-46d35ad, Gist, SublimeCodeIntel, Git, sublime-github, SyncedSideBar, C++, Vintage, Emmet, LiveStyle, Sublimerge Pro]
unloading plugin Emmet.emmet-plugin
reloading Packages/Emmet/Emmet.sublime-settings
reloading Packages/Emmet/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
generating syntax summary
found 5 files for base name Default.sublime-keymap
found 3 files for base name Main.sublime-menu
unloading plugin LiveStyle.livestyle
Emmet LiveStyle: Stopping server
reloading Packages/LiveStyle/LiveStyle.sublime-settings
found 3 files for base name Main.sublime-menu
unloading plugin Sublimerge Pro.Sublimerge2
found 5 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 3 files for base name Main.sublime-menu
found 1 files for base name Default.sublime-theme
found 4 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
ERROR:tornado.application:Exception in I/O handler for fd 332
Traceback (most recent call last):
  File "C:\Documents and Settings\FlastA\Application Data\Sublime Text 3\Installed Packages\LiveStyle.sublime-package\tornado\ioloop.py", line 672, in start
    self._handlers[fd](fd, events)
KeyError: 332
theme loaded
loading pointer bindings
theme loaded
loading pointer bindings
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Package Control.sublime-settings
Package Control: Upgraded Emmet to v2013.08.29.08.10.29
ignored packages updated to: [SideBarEnhancements, C++, keeganstreet-sublime-elfinder-46d35ad, SublimeCodeIntel, Vintage, Sublimerge Pro, Git, LiveStyle, SyncedSideBar, Rails, SideBarGit, sublime-github, Gist]
found 1 files for base name Default.sublime-theme
reloading plugin Emmet.emmet-plugin
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 71, in reload_plugin
    m = imp.reload(m)
  File "X/imp.py", line 252, in reload
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "emmet-plugin in C:\Documents and Settings\FlastA\Application Data\Sublime Text 3\Installed Packages\Emmet.sublime-package", line 20, in <module>
  File "X/imp.py", line 252, in reload
zipimport.ZipImportError: bad local file header in C:\Documents and Settings\FlastA\Application Data\Sublime Text 3\Installed Packages\Emmet.sublime-package
reloading Packages/Emmet/Emmet.sublime-settings
reloading Packages/Emmet/Preferences.sublime-settings
generating syntax summary
found 5 files for base name Default.sublime-keymap
found 4 files for base name Main.sublime-menu
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
Package Control: Upgraded LiveStyle to v2013.08.30.12.41.49
ignored packages updated to: [SideBarEnhancements, C++, keeganstreet-sublime-elfinder-46d35ad, SublimeCodeIntel, Vintage, Sublimerge Pro, Git, SyncedSideBar, Rails, SideBarGit, sublime-github, Gist]
found 1 files for base name Default.sublime-theme
reloading plugin LiveStyle.livestyle
Emmet LiveStyle: Stopping server
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 71, in reload_plugin
    m = imp.reload(m)
  File "X/imp.py", line 252, in reload
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.**dict**)
  File "livestyle in C:\Documents and Settings\FlastA\Application Data\Sublime Text 3\Installed Packages\LiveStyle.sublime-package", line 30, in <module>
  File "X/imp.py", line 252, in reload
zipimport.ZipImportError: bad local file header in C:\Documents and Settings\FlastA\Application Data\Sublime Text 3\Installed Packages\LiveStyle.sublime-package
reloading Packages/LiveStyle/LiveStyle.sublime-settings
found 5 files for base name Main.sublime-menu
reloading Packages/User/Package Control.sublime-settings
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Package Control.sublime-settings
Package Control: Upgraded Sublimerge Pro to v2.2.6
ignored packages updated to: [SideBarEnhancements, C++, keeganstreet-sublime-elfinder-46d35ad, SublimeCodeIntel, Vintage, Git, SyncedSideBar, Rails, SideBarGit, sublime-github, Gist]
found 1 files for base name Default.sublime-theme
reloading plugin Sublimerge Pro.Sublimerge2
found 6 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 6 files for base name Main.sublime-menu
found 6 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
theme loaded
loading pointer bindings
loading pointer bindings
found 6 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
reloading Packages/User/Preferences.sublime-settings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
Writing file /C/Projects/Darwin/Darwin-UI-LookFeel/Darwin-UI/Content/Default/Styles/FleetAdmin_New.css with encoding UTF-8 (atomic)

**Comment by sergeche** [comment]
Looks like WinXP is not supported by socket server, sorry

**Comment by ghost** [comment]
Ah its an XP problem. Ok. I should be upgrading to Win 7 soon so I will give it another try then.
