### ISSUE TITLE
I habe no livestyle tab in inspector

### ISSUE THREAD

**Issue by homax** [emmetio/livestyle-sublime-old#89]
sublime console:

DPI scale: 1.25
startup, version: 3047 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/homax/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/homax/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 4
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/homax/AppData/Roaming/Sublime Text 3/Installed Packages
found 7 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 7 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 4 orphaned files: 0 total files: 174 cache hits: 170
pre session restore time: 0.13456
using gamma: 1.9 (err: 81.5966)
startup time: 0.19256
first paint time: 0.19556
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin Emmet.emmet-plugin
loaded 1067 snippets
reloading plugin JsFormat.js_formatter
reloading plugin LiveStyle.livestyle
reloading plugin Local History.history
reloading plugin Package Control.Package Control
reloading plugin livestyle-sublime-master.livestyle
plugins loaded
Traceback (most recent call last):
  File "C:\Users\homax\AppData\Roaming\Sublime Text 3\Packages\livestyle-sublime-master\livestyle.py", line 371, in start_plugin
    lsutils.diff.import_pyv8()
AttributeError: 'module' object has no attribute 'import_pyv8'
Emmet LiveStyle: Starting LiveStyle server on port 54000
Traceback (most recent call last):
  File "livestyle in C:\Users\homax\AppData\Roaming\Sublime Text 3\Installed Packages\LiveStyle.sublime-package", line 326, in start_plugin
  File "C:\Users\homax\AppData\Roaming\Sublime Text 3\Installed Packages\LiveStyle.sublime-package\lsutils\websockets.py", line 135, in start
  File "C:\Users\homax\AppData\Roaming\Sublime Text 3\Installed Packages\LiveStyle.sublime-package\tornado\tcpserver.py", line 117, in listen
  File "C:\Users\homax\AppData\Roaming\Sublime Text 3\Installed Packages\LiveStyle.sublime-package\tornado\netutil.py", line 91, in bind_sockets
OSError: [WinError 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт)
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2013-11-09 11:18:51, next run at 2013-11-09 12:18:51 or after

 errors in chrome console for background.html:

storage.get: Failed to open database: Corruption: 1 missing files; e.g.: .../000081.sst
    at t (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:16370)
    at Object.get (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:16701)
    at Object.get (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:20320)
    at o (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:20725)
    at chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:22620 background.html:1
Error in response to storage.get: TypeError: Cannot read property 'global' of undefined
    at t (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:16370)
    at Object.get (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:16701)
    at Object.get (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:20320)
    at o (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:20725)
    at chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:22620 background.html:1
storage.get: Failed to open database: Corruption: 1 missing files; e.g.: .../000081.sst
    at t (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:16370)
    at Object.get (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:16701)
    at i (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:17933)
    at l (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:18725)
    at c (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:18706)
    at Object.callback (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:19702) background.html:1
Error in response to storage.get: TypeError: Cannot read property 'pageSettings' of undefined
    at t (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:16370)
    at Object.get (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:16701)
    at i (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:17933)
    at l (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:18725)
    at c (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:18706)
    at Object.callback (chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/background.js:18:19702) background.html:1
Disconnecting devtools:27 background.js:18
Disconnecting devtools:23 background.js:18
Disconnecting devtools:23 background.js:18
Disconnecting devtools:23 background.js:18
Disconnecting devtools:151 background.js:18
Disconnecting devtools:151 background.js:18  

I have tried to reinstall chrome extension.
Chrome version: 30.0.1599.101 m
chrome extension: 0.8.2.830
extension for sublime: 2013.09.11.14.09.52
sublime: v3 build 3047

**Comment by sergeche** [comment]
Your Chrome is corrupted, check your disk/viruses status.
Also, looks like you have very old LiveStyle plugin for Sublime Text since current version doesn’t use PyV8 anymore. And you might have something running on 54000 TCP port, check for other instances of ST or (maybe) Vim which also have unofficial support of LiveStyle

**Comment by homax** [comment]
I've reinstalled google chrome and now livestyle works! thank you
